### ISSUE TITLE
Cannot validate argument on parameter 'Account'

### ISSUE THREAD

**Issue by Zuldan** [rsWinAutomationSupport/rsNTFSPermission#2]
Hi there, thank you for writing up this resource. 

I'm having an issue on Windows 2012R2 / WMF 5 April Preview.

I get the following error when running the configuration on a node.

Invoke-CimMethod : PowerShell DSC resource RS_rsNTFSPermission  failed to execute Test-TargetResource functionality with error message: Cannot validate argument on parameter 'Account'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again. 

Here is my configuration. It's almost identical to the example provided but produces the error above.

```
    NTFSPermission Permission1
    {
        Ensure = "Present"
        Account = "mydomain\myuser1"
        Access = "Allow"
        Path = "D:\Dir1"
        Rights = "ReadAndExecute"
    } 

    NTFSPermission Permission2
    {
        Ensure = "Present"
        Account = "mydomain\myuser2"
        Access = "Allow"
        Path = "D:\Dir2"
        Rights = "ReadAndExecute"
    } 
```

Any assistance would be greatly appreciated!

**Comment by leshkinski** [comment]
Hi,

This module is probably going to go away soon as all of its functionality is included in the 'PowerShellAccessControl' module available from Microsoft here: https://gallery.technet.microsoft.com/scriptcenter/PowerShellAccessControl-d3be7b83

I'd recommend looking into that if you would like to manage permissions via DSC.

We may restart the development work on this module in the future, but for now I'd use the above module to do what you need.

**Comment by Zuldan** [comment]
Thanks for the heads up.
